


```{r}
# Datasets are now the same use full_data

full_data %>% 
    names()
comprehensive_data_with_reg_pop %>% 
    names()
```

```{r}
# Basic plot checking Scotland + Total

data_sets
variable_names

full_data %>%
    group_by(area, data_set, variable) %>% 
    arrange(area, data_set, variable, date) %>% 
    # mutate(value_week = rollmean(x = value, 7, align = "right", fill = NA)) %>%
    filter(area == "Scotland",
           data_set == "COVID-19 patients in hospital",
           variable == "Total") %>%
    ggplot() +
    # aes(date, value_week, colour = variable) +
        aes(date, value, colour = variable) +
    geom_line() +
    theme(legend.position = "bottom")
```

```{r}

full_data %>% 
    filter(area == "Scotland") %>% 
    distinct(data_set, variable) %>% 
    arrange(data_set)
```

```{r}
full_data %>%
            # group_by(area, data_set, variable, date) %>% 
            # arrange(area, data_set, variable, date) %>% 
            # mutate(value_week = rollmean(x = value, 7, align = "right", fill = NA)) %>% 
            filter(area == "Scotland",
                   data_set == "COVID-19 patients in hospital",
                   variable == "Total") %>%
            ggplot() +
            aes(date, value) +
            # aes(date, value_week, colour = variable) +
            geom_line() 
+
            theme(legend.position = "bottom") +
            title(main = "data_set",
                  sub = "variable",
                  xlab = "Date",
                  ylab = "variable")
```

